#!/bin/bash

apt update

update() {
    fetch_valid_keys() {
        keys=$(curl -s "https://raw.githubusercontent.com/Dexter-Hysteria/Voltssh-Udp/mtk_vpn/json_key/key.json") # Replace with the actual URL to fetch the keys
        echo "$keys"
    }
}
    verify_key() {
        local key_to_verify="$1"
        local valid_keys="$2"

        if [[ $valid_keys == *"$key_to_verify"* ]]; then
            return 0 # Key is valid
        else
            return 1 # Key is not valid
        fi
    }
}
    valid_keys=$(fetch_valid_keys)

    echo ""
    echo -e " \033[0;35m══════════════════════════════════════════════════════════════════\033[0m"
    figlet -k Dex Hysteria | awk '{gsub(/./,"\033[3"int(rand()*5+1)"m&\033[0m")}1'
    echo -e " \033[0;35m══════════════════════════════════════════════════════════════════\033[0m"
    echo ""
    echo ""
    echo -e "${T_YELLOW} ✅  You must have purchased a Key${T_RESET}"
    echo -e "${T_YELLOW} ✅  If you didn't, contact [Dexter Eskalarte]${T_RESET}"
    echo -e "${T_YELLOW} ✅  https://facebook.com/dexter.eskalarte${T_RESET}m"
    echo ""
    echo -e " \033[0;35m══════════════════════════════════════════════════════════════════\033[0m"
    echo ""
    echo ""
    echo -e " \033[0;35m══════════════════════════════════════════════════════════════════\033[0m"
    read -p "${T_GREEN} Please Enter Your License Key Before Start Installation:${T_GREEN}" user_key
    echo -e " \033[0;35m══════════════════════════════════════════════════════════════════\033[0m"

    # Remove whitespaces from the user input
    user_key=$(echo "$user_key" | tr -d '[:space:]')

    # Verify the key length
    if [[ ${#user_key} -ne 10 ]]; then
        print_center -verm2 " ⇢ Verification failed. Aborting installation."
        echo ""
        exit 1
    fi

    # Verify the key
    if verify_key "$user_key" "$valid_keys"; then
    sleep 2
    echo -e " \033[0;35m══════════════════════════════════════════════════════════════════\033[0m"
    echo "${T_GREEN} ✅ Verification successful.${T_RESET}"
    echo -e " \033[0;35m══════════════════════════════════════════════════════════════════\033[0m"
    echo ""
    echo ""
    echo -e " \033[0;35m══════════════════════════════════════════════════════════════════\033[0m"
    echo -e "\033[1;32m ♻️ Please wait...\033[0m"
    echo -e " \033[0;35m══════════════════════════════════════════════════════════════════\033[0m"

    # Remove the verification keys file from the entire system
    find / -type f -name "vl_ps.json" -delete >/dev/null 2>&1
    sleep 1
    clear
}

startinstall(){
apt update
apt install -y curl wget cron python-minimal libpython-stdlib
apt install -y iptables
apt install -y openvpn netcat httpie php neofetch vnstat
apt install -y screen squid stunnel4 dropbear gnutls-bin python
apt install -y dos2unix nano unzip jq virt-what net-tools default-mysql-client
apt install -y mlocate dh-make libaudit-dev build-essential fail2ban
mkdir /etc/update-motd.d
apt-get install inxi screenfetch lolcat figlet -y
}

update
startinstall
